[Theme]
Current=balos-matrix
CursorTheme=breeze_cursors
Font=JetBrainsMono Nerd Font

[General]
Numlock=on
DefaultSession=plasma.desktop
InputMethod=

[Wayland]
SessionDir=/usr/share/wayland-sessions
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1

[Autologin]
Relogin=false
Session=
User=
