[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 10
ILoveCandy
DisableDownloadTimeout

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Chaotic-AUR: prebuilt AUR packages (faster than AUR helpers)
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist

# BlackArch: 2800+ pentesting tools
[blackarch]
SigLevel = Optional TrustAll
Include = /etc/pacman.d/blackarch-mirrorlist

# BalOS local repo (custom kernel + tools)
[balos]
SigLevel = Never
Server = file:///balos-repo
